### ISSUE TITLE
No CI

### ISSUE THREAD

**Issue by local-minimum** [Odin-SMR/qqjobs#18]
Make CI

**Comment by joakimmoller** [comment]
https://jenkins.molflow.com/job/odin/

Kanske inte är inställd på att köra PR?

**Comment by local-minimum** [comment]
mm eller att integrationen till github inte e fixad.

**Comment by local-minimum** [comment]
håller inte med om att det e invalid eftersom vi inte har github integration på PRs, se https://github.com/Odin-SMR/qqjobs/pull/17
