### ISSUE TITLE
Security warning for pycrypto

### ISSUE THREAD

**Issue by skymandr** [Odin-SMR/qqjobs#5]
Investigate what to do, fix if possible. This might also be related to the qsmr-worker-images and odin-api.

GitHub has helpfully and automagically infomed us of the following:

> Known moderate severity security vulnerability detected in pycrypto <= 2.6.1 defined in requirements.txt.

**Comment by local-minimum** [comment]
Wasn't this resolved by #3 ?

**Comment by local-minimum** [comment]
We can use the same code we have but:

> For symmetric key cryptography:
> 
>     Symmetric ciphers do not have ECB as default mode anymore.
>     ECB is not semantically secure and it exposes correlation across blocks.
>     An expression like AES.new(key) will now fail.
>     If ECB is the desired mode, one has to explicitly use AES.new(key, AES.MODE_ECB).
> 

Which to me sounds like our encryption method itself since we use `AES.MODE_ECB` is problematic.

**Comment by local-minimum** [comment]
It seems relatively simple to change encryption mode: https://pycryptodome.readthedocs.io/en/latest/src/examples.html#encrypt-data-with-aes but I need to know which repositories and what to do besides updating them.
